import { Round, UNIT } from './round';
export const DEMO_WALLET = 'demo-you';
export function demoRounds(now: number): Round[] {
  const week = 7 * 86400;
  return [
    {
      id: 'laptop-fund',
      name: 'The laptop fund',
      emoji: '↗',
      creator: DEMO_WALLET,
      amount: 20 * UNIT,
      periodSeconds: week,
      periods: 5,
      startsAt: now - 2 * week - 86400,
      maxMembers: 8,
      bond: 100 * UNIT,
      color: '#E6EFD8',
      members: [
        {
          wallet: DEMO_WALLET,
          name: 'You',
          deposited: 40 * UNIT,
          paidPeriods: [0, 1],
          bond: 100 * UNIT,
          withdrawn: false,
        },
        {
          wallet: 'ada',
          name: 'Ada',
          deposited: 60 * UNIT,
          paidPeriods: [0, 1, 2],
          bond: 100 * UNIT,
          withdrawn: false,
        },
        {
          wallet: 'chidi',
          name: 'Chidi',
          deposited: 40 * UNIT,
          paidPeriods: [0, 1],
          bond: 100 * UNIT,
          withdrawn: false,
        },
        {
          wallet: 'sarah',
          name: 'Sarah',
          deposited: 60 * UNIT,
          paidPeriods: [0, 1, 2],
          bond: 100 * UNIT,
          withdrawn: false,
        },
      ],
    },
    {
      id: 'december-outside',
      name: 'December, outside',
      emoji: '☀',
      creator: DEMO_WALLET,
      amount: 25 * UNIT,
      periodSeconds: week,
      periods: 8,
      startsAt: now + 86400,
      maxMembers: 6,
      bond: 0,
      color: '#F5E5CF',
      members: [
        {
          wallet: DEMO_WALLET,
          name: 'You',
          deposited: 0,
          paidPeriods: [],
          bond: 0,
          withdrawn: false,
        },
        { wallet: 'ada', name: 'Ada', deposited: 0, paidPeriods: [], bond: 0, withdrawn: false },
      ],
    },
    {
      id: 'little-wins',
      name: 'Little wins club',
      emoji: '✳',
      creator: 'ada',
      amount: 10 * UNIT,
      periodSeconds: week,
      periods: 4,
      startsAt: now - 5 * week,
      maxMembers: 5,
      bond: 0,
      color: '#E9E1F2',
      members: [
        {
          wallet: DEMO_WALLET,
          name: 'You',
          deposited: 40 * UNIT,
          paidPeriods: [0, 1, 2, 3],
          bond: 0,
          withdrawn: false,
        },
        {
          wallet: 'ada',
          name: 'Ada',
          deposited: 20 * UNIT,
          paidPeriods: [0, 1],
          bond: 0,
          withdrawn: false,
        },
      ],
    },
    {
      id: 'weekend-crew',
      name: 'Weekend crew',
      emoji: '☀',
      creator: 'sarah',
      amount: 5 * UNIT,
      periodSeconds: week,
      periods: 4,
      startsAt: now + 86400,
      maxMembers: 5,
      bond: 0,
      color: '#F5E5CF',
      members: [
        {
          wallet: 'sarah',
          name: 'Sarah',
          deposited: 0,
          paidPeriods: [],
          bond: 0,
          withdrawn: false,
        },
      ],
    },
  ];
}
