use anchor_lang::prelude::*;
use anchor_spl::token::{self, Mint, Token, TokenAccount, TransferChecked};

// Address generated by scripts/init-program.mjs; deployment key stays in ignored .local/.
declare_id!("H2TwAXbeHpFadykMkrjpfEnhTTapTQ9gWiXs31tKh3Gw");

#[program]
pub mod round {
    use super::*;

    pub fn create_round(ctx: Context<CreateRound>, nonce: u64, args: RoundArgs) -> Result<()> {
        let now = Clock::get()?.unix_timestamp;
        require!(!args.name.trim().is_empty() && args.name.as_bytes().len() <= 96, RoundError::InvalidRules);
        require!(args.amount > 0 && args.periods > 0 && args.periods <= 52, RoundError::InvalidRules);
        require!(args.period_seconds >= 30 && args.period_seconds <= 31 * 86400, RoundError::InvalidRules);
        require!(args.starts_at > now && args.max_members >= 2 && args.max_members <= 20, RoundError::InvalidRules);
        require!(ctx.accounts.savings_mint.key() != ctx.accounts.bond_mint.key(), RoundError::InvalidMint);
        args.amount.checked_mul(args.periods as u64).ok_or(RoundError::Overflow)?;
        let duration = args.period_seconds.checked_mul(args.periods as i64).ok_or(RoundError::Overflow)?;
        let ends_at = args.starts_at.checked_add(duration).ok_or(RoundError::Overflow)?;
        let r = &mut ctx.accounts.round;
        r.creator = ctx.accounts.creator.key();
        r.nonce = nonce;
        r.name = args.name;
        r.savings_mint = ctx.accounts.savings_mint.key();
        r.bond_mint = ctx.accounts.bond_mint.key();
        r.amount = args.amount;
        r.bond_amount = args.bond_amount;
        r.period_seconds = args.period_seconds;
        r.periods = args.periods;
        r.starts_at = args.starts_at;
        r.ends_at = ends_at;
        r.max_members = args.max_members;
        r.member_count = 0;
        r.bump = ctx.bumps.round;
        Ok(())
    }

    pub fn join_round(ctx: Context<JoinRound>) -> Result<()> {
        let r = &mut ctx.accounts.round;
        require!(Clock::get()?.unix_timestamp < r.starts_at, RoundError::JoiningClosed);
        require!(r.member_count < r.max_members, RoundError::Full);
        let member = &mut ctx.accounts.member;
        member.round = r.key();
        member.owner = ctx.accounts.owner.key();
        member.deposited = 0;
        member.paid_mask = 0;
        member.bond_deposited = r.bond_amount;
        member.withdrawn = false;
        member.bump = ctx.bumps.member;
        if r.bond_amount > 0 {
            token::transfer_checked(CpiContext::new(ctx.accounts.token_program.to_account_info(), TransferChecked {
                from: ctx.accounts.owner_bond.to_account_info(),
                mint: ctx.accounts.bond_mint.to_account_info(),
                to: ctx.accounts.bond_vault.to_account_info(),
                authority: ctx.accounts.owner.to_account_info(),
            }), r.bond_amount, ctx.accounts.bond_mint.decimals)?;
        }
        r.member_count = r.member_count.checked_add(1).ok_or(RoundError::Overflow)?;
        Ok(())
    }

    pub fn contribute(ctx: Context<Contribute>) -> Result<()> {
        let r = &ctx.accounts.round;
        let now = Clock::get()?.unix_timestamp;
        let bit = contribution_bit(r.starts_at, r.ends_at, r.period_seconds, now)?;
        let member = &mut ctx.accounts.member;
        require!(!member.withdrawn, RoundError::AlreadyWithdrawn);
        require!(member.paid_mask & bit == 0, RoundError::AlreadyPaid);
        token::transfer_checked(CpiContext::new(ctx.accounts.token_program.to_account_info(), TransferChecked {
            from: ctx.accounts.owner_savings.to_account_info(),
            mint: ctx.accounts.savings_mint.to_account_info(),
            to: ctx.accounts.savings_vault.to_account_info(),
            authority: ctx.accounts.owner.to_account_info(),
        }), r.amount, ctx.accounts.savings_mint.decimals)?;
        member.deposited = member.deposited.checked_add(r.amount).ok_or(RoundError::Overflow)?;
        member.paid_mask |= bit;
        emit!(ContributionMade { round: r.key(), owner: member.owner, period: bit.trailing_zeros() as u8, amount: r.amount });
        Ok(())
    }

    pub fn withdraw(ctx: Context<Withdraw>) -> Result<()> {
        require!(Clock::get()?.unix_timestamp >= ctx.accounts.round.ends_at, RoundError::Locked);
        require!(!ctx.accounts.member.withdrawn, RoundError::AlreadyWithdrawn);
        let member = &ctx.accounts.member;
        require!(member.deposited > 0 || member.bond_deposited > 0, RoundError::NothingToWithdraw);
        let round_key = ctx.accounts.round.key();
        let owner_key = ctx.accounts.owner.key();
        let bump = [member.bump];
        let seeds: &[&[u8]] = &[b"member", round_key.as_ref(), owner_key.as_ref(), &bump];
        let signer = &[seeds];
        // No completion predicate: incomplete members receive exactly the same refund rights.
        if member.deposited > 0 {
            token::transfer_checked(CpiContext::new_with_signer(ctx.accounts.token_program.to_account_info(), TransferChecked {
                from: ctx.accounts.savings_vault.to_account_info(), mint: ctx.accounts.savings_mint.to_account_info(),
                to: ctx.accounts.owner_savings.to_account_info(), authority: member.to_account_info(),
            }, signer), member.deposited, ctx.accounts.savings_mint.decimals)?;
        }
        if member.bond_deposited > 0 {
            token::transfer_checked(CpiContext::new_with_signer(ctx.accounts.token_program.to_account_info(), TransferChecked {
                from: ctx.accounts.bond_vault.to_account_info(), mint: ctx.accounts.bond_mint.to_account_info(),
                to: ctx.accounts.owner_bond.to_account_info(), authority: member.to_account_info(),
            }, signer), member.bond_deposited, ctx.accounts.bond_mint.decimals)?;
        }
        emit!(SavingsReturned { round: round_key, owner: owner_key, savings: member.deposited,
            bond: member.bond_deposited, completed: member.paid_mask.count_ones() == ctx.accounts.round.periods as u32 });
        ctx.accounts.member.withdrawn = true;
        Ok(())
    }
}

fn contribution_bit(starts_at: i64, ends_at: i64, period_seconds: i64, now: i64) -> Result<u64> {
    require!(now >= starts_at, RoundError::NotStarted);
    require!(now < ends_at, RoundError::Ended);
    let period = (now - starts_at) / period_seconds;
    1u64.checked_shl(period as u32).ok_or_else(|| error!(RoundError::Overflow))
}

#[derive(AnchorSerialize, AnchorDeserialize, Clone)]
pub struct RoundArgs {
    pub name: String, pub amount: u64, pub bond_amount: u64, pub period_seconds: i64,
    pub periods: u8, pub starts_at: i64, pub max_members: u8,
}

#[account]
#[derive(InitSpace)]
pub struct SavingsRound {
    pub creator: Pubkey, pub nonce: u64,
    #[max_len(96)] pub name: String,
    pub savings_mint: Pubkey, pub bond_mint: Pubkey,
    pub amount: u64, pub bond_amount: u64, pub period_seconds: i64,
    pub periods: u8, pub starts_at: i64, pub ends_at: i64,
    pub max_members: u8, pub member_count: u8, pub bump: u8,
}

#[account]
#[derive(InitSpace)]
pub struct Member {
    pub round: Pubkey, pub owner: Pubkey, pub deposited: u64, pub bond_deposited: u64,
    pub paid_mask: u64, pub withdrawn: bool, pub bump: u8,
}

#[derive(Accounts)]
#[instruction(nonce: u64)]
pub struct CreateRound<'info> {
    #[account(mut)] pub creator: Signer<'info>,
    #[account(init, payer = creator, space = 8 + SavingsRound::INIT_SPACE,
        seeds = [b"round", creator.key().as_ref(), &nonce.to_le_bytes()], bump)]
    pub round: Account<'info, SavingsRound>,
    pub savings_mint: Account<'info, Mint>, pub bond_mint: Account<'info, Mint>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct JoinRound<'info> {
    #[account(mut)] pub owner: Signer<'info>,
    #[account(mut, has_one = savings_mint, has_one = bond_mint)] pub round: Account<'info, SavingsRound>,
    #[account(init, payer = owner, space = 8 + Member::INIT_SPACE,
        seeds = [b"member", round.key().as_ref(), owner.key().as_ref()], bump)]
    pub member: Account<'info, Member>,
    pub savings_mint: Account<'info, Mint>, pub bond_mint: Account<'info, Mint>,
    #[account(init, payer = owner, seeds = [b"savings", member.key().as_ref()], bump,
        token::mint = savings_mint, token::authority = member)] pub savings_vault: Account<'info, TokenAccount>,
    #[account(init, payer = owner, seeds = [b"bond", member.key().as_ref()], bump,
        token::mint = bond_mint, token::authority = member)] pub bond_vault: Account<'info, TokenAccount>,
    #[account(mut, token::mint = bond_mint, token::authority = owner)] pub owner_bond: Account<'info, TokenAccount>,
    pub token_program: Program<'info, Token>, pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct Contribute<'info> {
    pub owner: Signer<'info>,
    #[account(has_one = savings_mint)] pub round: Account<'info, SavingsRound>,
    #[account(mut, seeds = [b"member", round.key().as_ref(), owner.key().as_ref()], bump = member.bump,
        has_one = round, has_one = owner)] pub member: Account<'info, Member>,
    pub savings_mint: Account<'info, Mint>,
    #[account(mut, seeds = [b"savings", member.key().as_ref()], bump,
        token::mint = savings_mint, token::authority = member)] pub savings_vault: Account<'info, TokenAccount>,
    #[account(mut, token::mint = savings_mint, token::authority = owner)] pub owner_savings: Account<'info, TokenAccount>,
    pub token_program: Program<'info, Token>,
}

#[derive(Accounts)]
pub struct Withdraw<'info> {
    pub owner: Signer<'info>,
    #[account(has_one = savings_mint, has_one = bond_mint)] pub round: Account<'info, SavingsRound>,
    #[account(mut, seeds = [b"member", round.key().as_ref(), owner.key().as_ref()], bump = member.bump,
        has_one = round, has_one = owner)] pub member: Account<'info, Member>,
    pub savings_mint: Account<'info, Mint>, pub bond_mint: Account<'info, Mint>,
    #[account(mut, seeds = [b"savings", member.key().as_ref()], bump,
        token::mint = savings_mint, token::authority = member)] pub savings_vault: Account<'info, TokenAccount>,
    #[account(mut, seeds = [b"bond", member.key().as_ref()], bump,
        token::mint = bond_mint, token::authority = member)] pub bond_vault: Account<'info, TokenAccount>,
    #[account(mut, token::mint = savings_mint, token::authority = owner)] pub owner_savings: Account<'info, TokenAccount>,
    #[account(mut, token::mint = bond_mint, token::authority = owner)] pub owner_bond: Account<'info, TokenAccount>,
    pub token_program: Program<'info, Token>,
}

#[event]
pub struct ContributionMade { pub round: Pubkey, pub owner: Pubkey, pub period: u8, pub amount: u64 }
#[event]
pub struct SavingsReturned { pub round: Pubkey, pub owner: Pubkey, pub savings: u64, pub bond: u64, pub completed: bool }

#[error_code]
pub enum RoundError {
    #[msg("Invalid immutable ROUND rules")] InvalidRules,
    #[msg("Savings and commitment mints must differ")] InvalidMint,
    #[msg("Arithmetic overflow")] Overflow,
    #[msg("Joining closes at the start time")] JoiningClosed,
    #[msg("The ROUND is full")] Full,
    #[msg("This ROUND has not started")] NotStarted,
    #[msg("This ROUND has ended")] Ended,
    #[msg("This period has already been paid")] AlreadyPaid,
    #[msg("Savings remain locked until the end time")] Locked,
    #[msg("Savings have already been returned")] AlreadyWithdrawn,
    #[msg("No savings or commitment lock to withdraw")] NothingToWithdraw,
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn contribution_boundaries() {
        assert!(contribution_bit(1000, 1180, 60, 999).is_err());
        assert_eq!(contribution_bit(1000, 1180, 60, 1000).unwrap(), 1);
        assert_eq!(contribution_bit(1000, 1180, 60, 1059).unwrap(), 1);
        assert_eq!(contribution_bit(1000, 1180, 60, 1060).unwrap(), 2);
        assert_eq!(contribution_bit(1000, 1180, 60, 1179).unwrap(), 4);
        assert!(contribution_bit(1000, 1180, 60, 1180).is_err());
    }
}
